name: NX for AI fix
description: Nx Cloud fixes - https://nx.dev/ci/features/self-healing-ci

inputs:
  LOG:
    required: false
    type: boolean
    default: true

runs:
  using: composite
  steps:
    - name: cloud-cli | nx/AI fix
      if: always()
      shell: bash
      run: |
        npx nx fix-ci

    - name: action | LOG
      if: always()
      uses: vezham/vx-fe-deployer/.github/actions/common/log-artifact@timeline
