name: Release Check
description: Check for packages that need to be released using changesets

inputs:
  GITHUB_TOKEN:
    required: true
    type: string
  NPM_TOKEN:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: ci-setup | Install jq
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update
          sudo apt-get install -y jq
        fi

    - name: ci-setup | Check for releases
      id: check
      shell: bash
      run: | # npm whoami
        bash ${{ github.action_path }}/bin/main.sh
      # env:
      #   GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      #   NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
