name: changesets for release
description: Sets up Changesets for NPM release

inputs:
  GITHUB_TOKEN:
    required: true
    type: string
  NPM_TOKEN:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: ci-setup | LOG
      uses: vezham/vx-fe-deployer/.github/actions/common/log-setup@timeline

    - name: checklist-pr | [NPM] create release PR
      if: github.event_name != 'pull_request'
      id: changesets
      uses: changesets/action@v1
      with:
        # publish: pnpm changeset publish | ${{ steps.release-check.outputs.publish }} | echo "wjdlz/NOTE | INIT checklist-publish"
        # publish: pnpm publish -r
        # version: pnpm changeset version
        commit: 'ci(changesets): version packages'
        title: 'ci(changesets): :package: release packages'
        # setupGitUser: false
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}

    - name: checklist-release | [NPM] publish
      if: |
        github.event_name == 'pull_request' &&
        github.event.pull_request.merged == true &&
        contains(github.event.pull_request.title, 'ci(changesets): :package: release packages')
      uses: vezham/vx-fe-deployer/.github/actions/changesets/checklist-release@timeline
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
