name: Upload Logs to artifact
description: Upload the logs for debugging

runs:
  using: composite
  steps:
    - name: logs | e2e
      continue-on-error: true
      shell: bash
      run: |
        mkdir -p .vezham
        mkdir -p dist/.playwright
        cp -R dist/.playwright/ .vezham/playwright/
        echo "logs -> playwright-report"

    - name: logs | dir
      shell: bash
      run: |
        mkdir -p .vezham
        cp -R .vezham/ vx-ci/
        echo "logs -> artifact"
        pwd
        ls

    - name: ci-setup | Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: vx-ci-artifact
        path: vx-ci/
        retention-days: 30
