name: Extract credentials
description: Check for credentials that need to be used for deploy

runs:
  using: composite
  steps:
    # wjdlz/TODO: ci-setup | fetch-credentials - via vezham CI host
    - name: ci-setup | extract $ENV_TOKENS
      id: extract-credentials
      shell: bash
      run: |
        # @vx/NOTE: save token to temporary file
        echo '${{ secrets.GCP_SA_KEY }}' > token.json

        # @vx/NOTE: extract & mask credentials
        bash ${{ github.action_path }}/bin/main.sh token.json "$GITHUB_OUTPUT"

        # @vx/NOTE: clean up
        rm token.json

    - name: ci-setup | gen $ENV_TOKENS
      id: gen-env-tokens
      env:
        GCP_PROJECT_ID: ${{ steps.extract-credentials.outputs.GCP_PROJECT_ID }}
      run: |
        {
          echo "GCP_PROJECT_ID=$GCP_PROJECT_ID"
        } >> $GITHUB_ENV
