name: Release Check
description: Check for packages that need to be released using changesets

runs:
  using: composite
  steps:
    - name: ci-setup | Install jq
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update
          sudo apt-get install -y jq
        fi

    - name: ci-setup | Check for releases
      id: check
      shell: bash
      run: |
        # Make the check script executable
        chmod +x ${{ github.action_path }}/scripts/index.js

        # Run the check script
        node ${{ github.action_path }}/scripts/index.js

        # Batch the check script
        bash ${{ github.action_path }}/bin/main.sh
