name: NX for release
description: Sets up NX for NPM release

inputs:
  GITHUB_TOKEN:
    required: true
    type: string
  NPM_TOKEN:
    required: true
    type: string
  NPM_PROVENANCE:
    required: false
    type: boolean
    default: true
  version:
    required: false
    type: string
    default: ''

runs:
  using: composite
  steps:
    - name: ci-setup | LOG
      uses: vezham/vx-fe-deployer/.github/actions/common/log-setup@timeline

    - name: checklist-release | [NPM] publish
      shell: bash
      run: |
        pnpm nx run @vx:@vx-ws/release --version=${{ inputs.version }}
      # pnpm v:ws:release --version=${{ inputs.version }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
        NPM_CONFIG_PROVENANCE: ${{ inputs.NPM_PROVENANCE }}
