name: Log Setup
description: Log the setup for debugging

runs:
  using: composite
  steps:
    - name: ci-setup | SHA
      uses: vezham/vx-fe-deployer/.github/actions/common/setup-sha@timeline

    - name: logs | dir
      shell: bash
      run: |
        echo $SHA
        pwd
      # ls
