name: Gen Build
description: Gen Build for the apps

runs:
  using: composite
  steps:
    - name: setup | app-icon
      uses: vezham/vx-deployer/.github/actions/apps-desktop/setup-icons@timeline

    - name: cli | package
      shell: bash
      run: |
        pnpm package

    - name: cli | build & publish
      if: runner.os == 'macOS'
      shell: bash
      run: |
        pnpm run make
      # pnpm run publish

    # - name: cli | build & publish
    #   shell: bash
    #   run: |
    #     pnpm run make
    #     pnpm run publish
    #     pnpm run publish --no-git-checks

    # - name: logs | dir
    #   shell: bash
    #   run: |
    #     pwd
    #     cd build
    #     pwd
    #     ls
